// Generated by tools/generate-analytics-inventory.mjs. IDs only; no UI text or content.
export const ANALYTICS_CONTROLS: Record<string, { kind: 'button' | 'link' | 'card'; excluded: boolean }> = {
  "app-button-01": {
    "kind": "button",
    "excluded": true
  },
  "app-button-02": {
    "kind": "button",
    "excluded": false
  },
  "app-button-03": {
    "kind": "button",
    "excluded": false
  },
  "app-button-04": {
    "kind": "button",
    "excluded": false
  },
  "app-button-05": {
    "kind": "button",
    "excluded": false
  },
  "app-button-06": {
    "kind": "button",
    "excluded": false
  },
  "app-button-07": {
    "kind": "button",
    "excluded": false
  },
  "app-button-08": {
    "kind": "button",
    "excluded": true
  },
  "app-button-09": {
    "kind": "button",
    "excluded": true
  },
  "app-button-10": {
    "kind": "button",
    "excluded": true
  },
  "ai-chat-mode-selection-modal-button-01": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-mode-selection-modal-button-02": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-mode-selection-modal-button-03": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-mode-selection-modal-button-04": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-mode-selection-modal-button-05": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-view-button-01": {
    "kind": "button",
    "excluded": false
  },
  "a-i-chat-view-action-01": {
    "kind": "card",
    "excluded": false
  },
  "ai-chat-view-button-02": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-view-button-03": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-view-button-04": {
    "kind": "button",
    "excluded": true
  },
  "ai-chat-view-button-05": {
    "kind": "button",
    "excluded": true
  },
  "ai-chat-view-button-06": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-view-button-07": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-view-button-08": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-view-button-09": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-view-button-10": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-view-button-11": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-view-button-12": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-view-button-13": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-view-button-14": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-view-button-15": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-view-button-16": {
    "kind": "button",
    "excluded": false
  },
  "a-i-chat-view-action-02": {
    "kind": "card",
    "excluded": false
  },
  "ai-chat-view-button-17": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-view-button-18": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-view-button-19": {
    "kind": "button",
    "excluded": true
  },
  "ai-chat-view-button-20": {
    "kind": "button",
    "excluded": true
  },
  "ai-chat-view-button-21": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-view-button-22": {
    "kind": "button",
    "excluded": false
  },
  "ai-chat-view-button-23": {
    "kind": "button",
    "excluded": false
  },
  "a-i-error-report-modal-action-01": {
    "kind": "card",
    "excluded": false
  },
  "ai-error-report-modal-button-01": {
    "kind": "button",
    "excluded": true
  },
  "ai-error-report-modal-button-02": {
    "kind": "button",
    "excluded": true
  },
  "ai-error-report-modal-button-03": {
    "kind": "button",
    "excluded": true
  },
  "ai-explain-settings-modal-button-01": {
    "kind": "button",
    "excluded": false
  },
  "ai-explain-settings-modal-button-02": {
    "kind": "button",
    "excluded": false
  },
  "adult-verification-modal-button-01": {
    "kind": "button",
    "excluded": true
  },
  "adult-verification-modal-button-02": {
    "kind": "button",
    "excluded": true
  },
  "analytics-consent-button-01": {
    "kind": "button",
    "excluded": true
  },
  "analytics-consent-button-02": {
    "kind": "button",
    "excluded": true
  },
  "analytics-consent-button-03": {
    "kind": "button",
    "excluded": true
  },
  "analytics-consent-button-04": {
    "kind": "button",
    "excluded": true
  },
  "balance-game-section-button-01": {
    "kind": "button",
    "excluded": false
  },
  "balance-game-section-button-02": {
    "kind": "button",
    "excluded": false
  },
  "balance-game-section-button-03": {
    "kind": "button",
    "excluded": false
  },
  "balance-game-section-button-04": {
    "kind": "button",
    "excluded": false
  },
  "balance-game-section-button-05": {
    "kind": "button",
    "excluded": false
  },
  "balance-game-section-self-button-01": {
    "kind": "button",
    "excluded": false
  },
  "create-story-modal-button-01": {
    "kind": "button",
    "excluded": false
  },
  "create-story-modal-button-02": {
    "kind": "button",
    "excluded": false
  },
  "create-story-modal-button-03": {
    "kind": "button",
    "excluded": false
  },
  "create-story-modal-button-04": {
    "kind": "button",
    "excluded": false
  },
  "crisis-support-modal-action-01": {
    "kind": "link",
    "excluded": false
  },
  "crisis-support-modal-action-02": {
    "kind": "link",
    "excluded": false
  },
  "crisis-support-modal-action-03": {
    "kind": "link",
    "excluded": false
  },
  "crisis-support-modal-action-04": {
    "kind": "link",
    "excluded": false
  },
  "crisis-support-modal-button-01": {
    "kind": "button",
    "excluded": true
  },
  "crisis-support-modal-button-02": {
    "kind": "button",
    "excluded": true
  },
  "delete-confirm-modal-button-01": {
    "kind": "button",
    "excluded": true
  },
  "delete-confirm-modal-button-02": {
    "kind": "button",
    "excluded": true
  },
  "header-action-01": {
    "kind": "card",
    "excluded": false
  },
  "header-button-01": {
    "kind": "button",
    "excluded": false
  },
  "header-button-02": {
    "kind": "button",
    "excluded": false
  },
  "login-prompt-modal-button-01": {
    "kind": "button",
    "excluded": false
  },
  "login-prompt-modal-button-02": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-action-01": {
    "kind": "card",
    "excluded": false
  },
  "my-page-view-button-01": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-action-04": {
    "kind": "link",
    "excluded": false
  },
  "my-page-view-button-02": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-action-02": {
    "kind": "link",
    "excluded": true
  },
  "my-page-view-button-03": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-button-04": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-button-05": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-button-06": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-button-07": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-button-08": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-button-09": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-button-10": {
    "kind": "button",
    "excluded": true
  },
  "my-page-view-button-11": {
    "kind": "button",
    "excluded": true
  },
  "my-page-view-button-12": {
    "kind": "button",
    "excluded": true
  },
  "my-page-view-button-13": {
    "kind": "button",
    "excluded": true
  },
  "my-page-view-button-14": {
    "kind": "button",
    "excluded": true
  },
  "my-page-view-button-15": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-button-19": {
    "kind": "button",
    "excluded": true
  },
  "my-page-view-button-20": {
    "kind": "button",
    "excluded": true
  },
  "my-page-view-button-21": {
    "kind": "button",
    "excluded": true
  },
  "my-page-view-button-22": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-button-23": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-button-24": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-button-25": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-button-26": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-button-27": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-button-28": {
    "kind": "button",
    "excluded": true
  },
  "my-page-view-button-29": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-button-30": {
    "kind": "button",
    "excluded": true
  },
  "my-page-view-button-31": {
    "kind": "button",
    "excluded": true
  },
  "my-page-view-button-32": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-button-33": {
    "kind": "button",
    "excluded": false
  },
  "my-page-view-button-34": {
    "kind": "button",
    "excluded": true
  },
  "my-page-view-action-05": {
    "kind": "link",
    "excluded": false
  },
  "my-page-view-button-35": {
    "kind": "button",
    "excluded": true
  },
  "my-page-view-action-03": {
    "kind": "link",
    "excluded": true
  },
  "my-page-view-button-36": {
    "kind": "button",
    "excluded": true
  },
  "my-page-view-button-37": {
    "kind": "button",
    "excluded": true
  },
  "my-page-view-button-38": {
    "kind": "button",
    "excluded": true
  },
  "my-page-view-button-39": {
    "kind": "button",
    "excluded": false
  },
  "navbar-button-01": {
    "kind": "button",
    "excluded": false
  },
  "navbar-button-02": {
    "kind": "button",
    "excluded": false
  },
  "navbar-button-03": {
    "kind": "button",
    "excluded": false
  },
  "premium-modal-button-01": {
    "kind": "button",
    "excluded": false
  },
  "premium-modal-button-02": {
    "kind": "button",
    "excluded": false
  },
  "premium-modal-button-03": {
    "kind": "button",
    "excluded": false
  },
  "premium-modal-button-04": {
    "kind": "button",
    "excluded": false
  },
  "report-modal-button-01": {
    "kind": "button",
    "excluded": true
  },
  "report-modal-button-02": {
    "kind": "button",
    "excluded": true
  },
  "report-modal-button-03": {
    "kind": "button",
    "excluded": true
  },
  "session-summary-card-button-01": {
    "kind": "button",
    "excluded": false
  },
  "session-summary-card-button-02": {
    "kind": "button",
    "excluded": false
  },
  "session-summary-card-button-03": {
    "kind": "button",
    "excluded": false
  },
  "session-summary-card-button-04": {
    "kind": "button",
    "excluded": false
  },
  "share-result-bar-button-01": {
    "kind": "button",
    "excluded": false
  },
  "share-result-bar-button-02": {
    "kind": "button",
    "excluded": false
  },
  "share-result-bar-button-03": {
    "kind": "button",
    "excluded": false
  },
  "story-card-button-01": {
    "kind": "button",
    "excluded": true
  },
  "story-card-action-01": {
    "kind": "card",
    "excluded": false
  },
  "story-card-button-02": {
    "kind": "button",
    "excluded": false
  },
  "story-card-button-03": {
    "kind": "button",
    "excluded": false
  },
  "story-card-button-04": {
    "kind": "button",
    "excluded": true
  },
  "story-card-button-05": {
    "kind": "button",
    "excluded": true
  },
  "story-card-button-06": {
    "kind": "button",
    "excluded": true
  },
  "story-card-button-07": {
    "kind": "button",
    "excluded": false
  },
  "story-card-button-08": {
    "kind": "button",
    "excluded": false
  },
  "story-card-button-09": {
    "kind": "button",
    "excluded": false
  },
  "story-card-button-10": {
    "kind": "button",
    "excluded": false
  },
  "story-card-button-11": {
    "kind": "button",
    "excluded": false
  },
  "story-card-button-12": {
    "kind": "button",
    "excluded": false
  },
  "story-card-button-13": {
    "kind": "button",
    "excluded": false
  },
  "story-card-button-14": {
    "kind": "button",
    "excluded": false
  },
  "story-detail-modal-action-01": {
    "kind": "card",
    "excluded": false
  },
  "story-detail-modal-button-01": {
    "kind": "button",
    "excluded": false
  },
  "story-detail-modal-button-02": {
    "kind": "button",
    "excluded": false
  },
  "story-detail-modal-button-03": {
    "kind": "button",
    "excluded": true
  },
  "story-detail-modal-button-04": {
    "kind": "button",
    "excluded": true
  },
  "story-detail-modal-button-05": {
    "kind": "button",
    "excluded": true
  },
  "story-detail-modal-button-06": {
    "kind": "button",
    "excluded": true
  },
  "story-detail-modal-button-07": {
    "kind": "button",
    "excluded": false
  },
  "story-detail-modal-button-08": {
    "kind": "button",
    "excluded": true
  },
  "story-detail-modal-action-02": {
    "kind": "link",
    "excluded": true
  },
  "story-detail-modal-button-09": {
    "kind": "button",
    "excluded": false
  },
  "story-detail-modal-button-10": {
    "kind": "button",
    "excluded": false
  },
  "story-detail-modal-button-11": {
    "kind": "button",
    "excluded": false
  },
  "story-detail-modal-button-12": {
    "kind": "button",
    "excluded": false
  },
  "story-detail-modal-button-13": {
    "kind": "button",
    "excluded": false
  },
  "story-detail-modal-button-14": {
    "kind": "button",
    "excluded": false
  },
  "story-detail-modal-button-15": {
    "kind": "button",
    "excluded": true
  },
  "story-detail-modal-button-16": {
    "kind": "button",
    "excluded": true
  },
  "story-detail-modal-button-17": {
    "kind": "button",
    "excluded": false
  },
  "story-detail-modal-button-18": {
    "kind": "button",
    "excluded": false
  },
  "story-detail-modal-button-19": {
    "kind": "button",
    "excluded": false
  },
  "story-detail-modal-button-20": {
    "kind": "button",
    "excluded": false
  },
  "story-detail-modal-action-03": {
    "kind": "card",
    "excluded": false
  },
  "story-detail-modal-button-21": {
    "kind": "button",
    "excluded": false
  },
  "weekly-top-banner-action-01": {
    "kind": "card",
    "excluded": false
  },
  "weekly-top-banner-button-01": {
    "kind": "button",
    "excluded": false
  },
  "weekly-top-banner-button-02": {
    "kind": "button",
    "excluded": false
  },
  "weekly-top-banner-self-button-01": {
    "kind": "button",
    "excluded": false
  },
  "welcome-modal-button-01": {
    "kind": "button",
    "excluded": false
  },
  "welcome-modal-button-02": {
    "kind": "button",
    "excluded": false
  },
  "welcome-modal-button-03": {
    "kind": "button",
    "excluded": false
  },
  "welcome-modal-button-04": {
    "kind": "button",
    "excluded": false
  },
  "welcome-modal-button-05": {
    "kind": "button",
    "excluded": false
  },
  "welcome-modal-button-06": {
    "kind": "button",
    "excluded": false
  },
  "welcome-modal-button-07": {
    "kind": "button",
    "excluded": false
  },
  "welcome-modal-button-08": {
    "kind": "button",
    "excluded": false
  },
  "welcome-modal-button-09": {
    "kind": "button",
    "excluded": false
  },
  "welcome-modal-button-10": {
    "kind": "button",
    "excluded": false
  },
  "welcome-modal-button-11": {
    "kind": "button",
    "excluded": false
  },
  "welcome-modal-button-12": {
    "kind": "button",
    "excluded": false
  },
  "welcome-modal-button-13": {
    "kind": "button",
    "excluded": false
  },
  "welcome-modal-button-14": {
    "kind": "button",
    "excluded": false
  },
  "welcome-modal-button-15": {
    "kind": "button",
    "excluded": false
  },
  "welcome-modal-button-16": {
    "kind": "button",
    "excluded": false
  }
};
export function getAnalyticsControl(id: unknown) {
  return typeof id === 'string' && Object.prototype.hasOwnProperty.call(ANALYTICS_CONTROLS, id) ? ANALYTICS_CONTROLS[id] : undefined;
}
